(() => {
// 新台词可添加 voice: 'resources/sound/...'；null 表示暂时无配音。
// 场景图片与专属配乐留空时，使用已有校园背景与 peace。
const scenes = {
  gate: { title: '第一幕 · 初来乍到', image: 'resources/scene/sight/1.jpg', music: null },
  yard: { title: '第二幕 · 操场集合', image: 'resources/scene/sight/yard_assembly.png', music: null },
  exercise: { title: '第三幕 · 少年起势', image: 'resources/scene/sight/wushu_practice.png', music: null },
};
const story = [
  { text: '多么好的上午啊！' },
  { text: '花儿在绽放。' },
  { text: '鸟儿在歌唱。' },
  { text: '新学期也开始了。' },
  { speaker: '我', text: '这就是高中吗……有点期待呢。' },
  { speaker: '我', text: '区区高中，不足挂齿，你豪王来了！', voice: 'resources/sound/human/male/school_open1.mp3' },
  { text: '从背后传来声音：' },
  { speaker: '？？？', text: 'Oi！小鬼，你刚才提到了豪王是吗？', voice: 'resources/sound/human/male/school_open2.mp3' },
  { event: 'jiahaoEntrance' },
  { speaker: '我', text: '你……也是来报到的？', voice: null },
  { speaker: '？？？', text: '嘉豪。嘉奖的嘉，豪迈的豪。先记住这个名字。', voice: null },
  { speaker: '我', text: '这学校报到之前，还要先报江湖名号吗？', voice: null },
  { text: '他把手从口袋里抽出来。我下意识站直了。', voice: null },
  { speaker: '嘉豪', text: '别紧张。你校服标签露出来了。', voice: null },
  { speaker: '我', text: '……谢谢。', voice: null },
  { speaker: '广播', text: '请高一年级全体同学到操场集合，准备进行武术操入门练习。', voice: null },
  { speaker: '我', text: '第一天就练武？原来高中真的是江湖。', voice: null },
  { speaker: '嘉豪', text: '走吧，大侠。先找到我们班，不然第一招就是迟到。', voice: null },
  { text: '我跟着嘉豪穿过人群。前方的口令声，渐渐清晰起来。', voice: null },
  { event: 'scene', scene: 'yard' },
  { text: '操场上，各班的队伍已经排开。我们赶在点名前站进了最后一排。', voice: null },
  { speaker: '体育老师', text: '同学们，前后左右留出距离。今天先熟悉动作，整齐比抢快重要。', voice: null },
  { speaker: '嘉豪', text: '听见没？刚才那股豪气，待会儿别全用在喊口号上。', voice: null },
  { speaker: '我', text: '放心，我已经准备好一鸣惊人了。', voice: null },
  { text: '嘉豪低头看了一眼我并得过分整齐的双脚，忍住了笑。', voice: null },
  { speaker: '体育老师', text: '先跟口令走一遍：预备、抱拳、起势。不会没关系，看示范，慢慢跟上。', voice: null },
  { speaker: '我', text: '原来第一课不是打败谁，是先别踩到旁边的人。', voice: null },
  { speaker: '嘉豪', text: '这就对了。跟上，我在旁边。', voice: null },
  { event: 'scene', scene: 'exercise' },
  { speaker: '体育老师', text: '全体都有——立正！', voice: null },
  { text: '操场渐渐安静下来。我收住笑，跟着队伍站好。', voice: null },
  { speaker: '体育老师', text: '抱拳，行礼！', voice: null },
  { text: '我学着示范抬起双手。身旁的嘉豪也认真地行了一礼。', voice: null },
  { speaker: '体育老师', text: '武术操，预备——起势！', voice: null },
  { speaker: '体育老师', text: '今天练一套“八式巡礼”。抱拳、鹤引、六合、虎步……每一式都有自己的落点。', voice: null },
  { speaker: '嘉豪', text: '先选你的行拳方式：守势求稳，刚势求准，游势靠连招聚气。别只盯着第三拍。', voice: null },
  { event: 'practice' },
  { speaker: '体育老师', text: state => state.practiceResult?.accuracy >= 80 ? '后排那位新同学，第一次就能守住八成节拍，不错！' : '第一遍乱一点没关系。记住：脚下有根，手上才有劲。', voice: null },
  { speaker: '我', text: state => state.practiceResult?.bestCombo >= 5 ? '刚才连起来的那几招……像有一股热气顺着手臂冲了出去。' : '呼……看着只是几拍，真正跟下来一点也不轻松。', voice: null },
  { speaker: '嘉豪', text: state => state.practiceResult?.style === 'fierce' ? '刚势很适合你。就是下次别把地板也当对手。' : state.practiceResult?.style === 'flowing' ? '游势？有眼光。招式之间的缝，才最考人。' : '守得挺稳。先把根扎住，以后才有资格谈快。', voice: null },
  { text: '风从队伍间穿过。刚才还各自凌乱的动作，渐渐汇成同一个节拍。', voice: null },
  { speaker: '体育老师', text: '最后一遍，不看我。听鼓点，也听你们身边的人。', voice: null },
  { text: '抱拳礼——操场安静了一瞬。', voice: null },
  { text: '鹤引清风——百余双手臂一齐展开。', voice: null },
  { text: '六合开门、虎步撼地——脚步落下，像远处传来一声闷雷。', voice: null },
  { text: '黑虎掏心！我踩中那一拍，拳风擦过袖口。', voice: null },
  { speaker: '嘉豪', text: '这次像点样子了，豪王。', voice: null },
  { speaker: '我', text: '你就等着吧。下次站在前排领操的人，说不定是我。', voice: null },
  { speaker: '嘉豪', text: '好啊。那我就站你旁边，专门看你同手同脚。', voice: null },
  { text: '下课铃越过钟楼。新学期的第一场较量没有输赢，却多了一个会在旁边提醒我的人。', voice: null },
  { speaker: '我', text: '我的高中生活，就从这一拍开始吧。', voice: null },
];

window.WushuStory = { scenes, story };
})();
