(() => {
  // 剧情与编排为原创。voice / music 为 null 时不请求新素材，沿用已有配乐。
  // when 控制台词是否出现；选择只影响剧情关系，不改变练习的判定窗口。
  const scenes = {
    gate: { title: '第一章 · 名字先记住', image: 'resources/scene/sight/1.jpg', music: 'school' },
    yard: { title: '第二章 · 后排也有节拍', image: 'resources/scene/sight/yard_assembly.png', music: 'school' },
    exercise: { title: '第三章 · 八式初试', image: 'resources/scene/sight/wushu_practice_homage.png', music: 'school' },
    lunch: { title: '第四章 · 被风吹乱的名单', image: 'resources/scene/sight/courtyard_wind_original.png', music: 'comedy' },
    relay: { title: '第五章 · 你的下一拍', image: 'resources/scene/sight/wushu_practice_homage.png', music: 'school' },
    afterSchool: { title: '终章 · 明天见', image: 'resources/scene/sight/1.jpg', music: 'school' },
  };
  const resultFor = (state, mode) => state.practiceResults?.[mode] || {};
  const challengeFor = (state, mode) => state.adventureResults?.[mode] || {};
  const endingFor = state => state.rapport >= 2 ? 'together' :
    state.courage >= 2 && resultFor(state, 'relay').accuracy >= 70 ? 'lead' : 'steady';
  const story = [
    { text: '多么好的上午啊！' },
    { text: '花儿在绽放。' },
    { text: '鸟儿在歌唱。' },
    { text: '新学期也开始了。' },
    { speaker: '我', text: '这就是高中吗……有点期待呢。', when: state => state.character === '女同学', voice: null },
    { speaker: '我', text: '区区高中，不足挂齿，你豪王来了！', when: state => state.character !== '女同学', voice: 'resources/sound/human/male/school_open1.mp3' },
    { speaker: '我', text: '“豪王到此一游”……开学第一天，留言板上就有人给自己起外号了？', when: state => state.character === '女同学', voice: null },
    { text: '从背后传来声音：' },
    { speaker: '？？？', text: 'Oi！小鬼，你刚才提到了豪王是吗？', voice: 'resources/sound/human/male/school_open2.mp3' },
    { event: 'jiahaoEntrance' },
    { speaker: '我', text: '你……也是来报到的？' },
    { speaker: '？？？', text: '嘉豪。嘉奖的嘉，豪迈的豪。先记住这个名字。' },
    { speaker: '我', text: '这学校报到之前，还要先报江湖名号吗？' },
    { text: '他把手从口袋里抽出来。我下意识站直了。' },
    { speaker: '嘉豪', text: '别紧张。你校服标签露出来了。' },
    {
      event: 'choice', id: 'first_reply', prompt: '把标签塞回去之后，你决定——',
      options: [
        { id: 'bold', label: '称号先借我一天。', detail: '顺着玩笑接一句。', effects: { courage: 1 }, reply: { speaker: '嘉豪', text: '行，试用期一天。放学前记得归还。' } },
        { id: 'friendly', label: '谢了，带我找找教室？', detail: '试着向新同学靠近一点。', effects: { rapport: 1 }, reply: { speaker: '嘉豪', text: '正好顺路。迷路了咱俩一起认。' } },
        { id: 'careful', label: '名字记住了，几班的？', detail: '先把有用的信息弄清楚。', effects: { focus: 1 }, reply: { speaker: '嘉豪', text: '高一三班。你也是？那江湖还挺小。' } },
      ],
    },
    { speaker: '我', text: state => state.choices?.first_reply === 'bold' ? '一天够了。我争取不把这个称号用坏。' : state.choices?.first_reply === 'friendly' ? '可以，迷路时你负责问路，我负责保持镇定。' : '高一三班，嘉豪。好，这比记一串新密码容易。' },
    { speaker: '广播', text: '请高一年级全体同学到操场集合，准备进行武术操入门练习。' },
    { speaker: '我', text: '第一天就练武？我的书包都还没找到落脚的地方。' },
    { speaker: '嘉豪', text: '走吧。先找到我们班，不然第一招就是迟到。' },
    { text: '我跟着嘉豪穿过人群。前方的口令声，渐渐清晰起来。' },
    { event: 'scene', scene: 'yard' },
    { text: '我们赶在点名前站进最后一排。阳光越过前排同学的肩膀，一格一格落在地上。' },
    { speaker: '体育老师', text: '前后左右留出距离。今天先熟悉动作，整齐比抢快重要。' },
    { speaker: '嘉豪', text: '最后一排有个好处：前面全是示范。坏处是，有时候示范也不会。' },
    { speaker: '我', text: '那我就挑看起来最有把握的那个。比如你。' },
    { speaker: '体育老师', text: '先记住四拍。每一式的重点不一定在同一拍，听清再动。' },
    { speaker: '我', text: '原来第一课是克制一下“我已经懂了”的冲动。' },
    { speaker: '嘉豪', text: '不错，理解得比我第一天快。' },
    { event: 'scene', scene: 'exercise' },
    { speaker: '体育老师', text: '全体都有——立正！' },
    { text: '操场渐渐安静下来。嘉豪收起笑，我也跟着站好。' },
    { speaker: '体育老师', text: '抱拳，行礼！' },
    { text: '衣袖轻轻擦过。我忽然觉得，刚才闹哄哄的一群人，好像真的成了一支队伍。' },
    { speaker: '体育老师', text: '今天走一套“八式巡礼”：向地术、六合、虎尊、香店、鸣鹤、檀家、咏春、罗汉八脉借一点形与劲。抱拳起，鹤引展，虎步落，最后归元。' },
    { speaker: '嘉豪', text: '不是把八套拳硬塞进八拍，是记住它们的脾气：有的稳根，有的合劲，有的刚猛，有的像鹤一样舒展。' },
    { speaker: '嘉豪', text: '守势宽容一点，刚势考准头，游势攒意气快。选顺手的，没人按名字收学费。' },
    { speaker: '体育老师', text: '每一式考的东西不同：礼要左右合拍，鹤要找准风门，虎步要蓄力落稳，罗汉推掌要把力量持续送出去。别只会追鼓点。' },
    { speaker: '嘉豪', text: '最后还有归元。前面忙得像体育游戏大会，最后一式却要你安静下来。挺会安排。' },
    { event: 'forms', title: '八式百炼 · 初试', id: 'standard' },
    { speaker: '体育老师', text: state => resultFor(state, 'standard').accuracy >= 80 ? '后排那位新同学，八项都抓住了重点。很好，接下来试着把不同的劲连成一套。' : '第一次练完了，先记住自己最顺的一式。下一次从它开始，再把不熟的规则一项项接回来。' },
    { speaker: '我', text: state => resultFor(state, 'standard').bestCombo >= 5 ? '规则一直在变，身体居然还是能一式接一式地跟上。' : '脑子说八种玩法都懂了，手说它还需要开个会。' },
    { speaker: '嘉豪', text: state => resultFor(state, 'standard').style === 'mixed' ? '八式八种规矩，你居然没把“回身”和“推山”按成同一个按钮。不错。' : resultFor(state, 'standard').style === 'fierce' ? '刚势选手。刚才那股认真劲儿，我先记下了。' : resultFor(state, 'standard').style === 'flowing' ? '游势挺适合你。连上以后，下一招像是自己找过来的。' : '守势挺好。慢慢来能站得住，比急着表现管用。' },
    { speaker: '体育老师', text: '休息。下午做接拍练习，两人轮流示范。体育委员，午休前把分组名单贴好。' },
    { event: 'scene', scene: 'lunch' },
    { text: '午间，风把体育委员手里的纸掀成一小群白鸟。我接住一张，嘉豪踩住了另一张的空白角。' },
    { speaker: '体育委员', text: '别让分组名单飞到水沟里！上面还有老师写的备注！' },
    { speaker: '我', text: '我这张写着“番茄炒蛋”。它负责哪一组？' },
    { speaker: '嘉豪', text: '背面。别看正面，看正面只会提前饿。' },
    {
      event: 'choice', id: 'scattered_notes', prompt: '几张纸散在队伍旁边，你先怎么帮忙？',
      options: [
        { id: 'together', label: '和嘉豪一张张收回来。', detail: '一人捡纸，一人压住，配合着来。', effects: { rapport: 1 }, reply: { speaker: '嘉豪', text: '你递，我压着。这次风想插队也没用。' } },
        { id: 'organize', label: '先把页码和班级对上。', detail: '把手里几张按顺序整理好。', effects: { focus: 1 }, reply: { speaker: '体育委员', text: '太好了，我刚才差点把菜单也贴上去。' } },
        { id: 'call_out', label: '叫住前面几个人一起捡。', detail: '主动招呼大家分头帮忙。', effects: { courage: 1 }, reply: { speaker: '同班同学', text: '收到！靠水沟那两张交给我们。' } },
      ],
    },
    { text: state => state.choices?.scattered_notes === 'together' ? '我负责追页码，嘉豪负责压住收回的纸。剩下几张还在风里打转。' : state.choices?.scattered_notes === 'organize' ? '我先看清页码，再朝散页跑去。找准顺序，应该比看见一张抓一张更快。' : '几个人应声分散开来。我盯住名单上的红色页码，免得把午饭菜单也混进去。' },
    { event: 'adventure', mode: 'paper', title: '风中名单', id: 'paper' },
    { speaker: '体育委员', text: state => challengeFor(state, 'paper').correct === challengeFor(state, 'paper').total ? challengeFor(state, 'paper').errors === 0 ? '一张没漏，顺序也全对！你是不是平时专门跟风抢东西？' : '名单齐了！中间那几张菜单我就当没看见。' : '先收回这些，剩下的我去水沟边找。至少班级和场地页都保住了。' },
    { speaker: '嘉豪', text: state => challengeFor(state, 'paper').grade === 'S' ? '眼睛挺快，手也没乱。看来豪王还兼任文书。' : '风比口令不讲道理。看清下一张再追，反而更快。' },
    { speaker: '嘉豪', text: '你看老师这句备注：“后排有人跟不上时，示范再慢一遍。”' },
    { speaker: '我', text: '我以为老师只看见前排。' },
    { speaker: '嘉豪', text: '我以前一直站后排。不是藏得好，是紧张的时候会把第一拍当第二拍。' },
    { text: '名单角上还有一行铅笔字：“搭档不是比较对象。”嘉豪把折起的纸角轻轻抚平。' },
    { speaker: '我', text: '所以你上午一直站我旁边，是来检查我的同手同脚？' },
    { speaker: '嘉豪', text: '本来是。后来发现，你能接住我说话，我也能接住你慢的那半拍。下午搭个档？' },
    { speaker: '我', text: '好。那先去吃饭，番茄炒蛋那一组不能等太久。' },
    { event: 'scene', scene: 'relay' },
    { speaker: '体育老师', text: '下午换个练法：先看搭档示范，再在自己的回合接上。要听见别人，也要留住自己的节拍。' },
    { speaker: '嘉豪', text: '我先示范，你再接。轮到我时先看提示，轮到你再出招，别抢我的回合。' },
    { text: '我们站到白线两侧。上午那点“别出错”的紧张，变成了“这次想接好”的期待。' },
    {
      event: 'choice', id: 'relay_plan', prompt: '开始前，给搭档留一句话。',
      options: [
        { id: 'listen', label: '我听着呢，放心起拍。', detail: '把注意力放在彼此的配合上。', effects: { rapport: 1 }, reply: { speaker: '嘉豪', text: '好。你接你的，我也会看着你。' } },
        { id: 'lead', label: '下一轮，我也想试试带头。', detail: '把想站到前面的念头说出来。', effects: { courage: 1 }, reply: { speaker: '嘉豪', text: '那就先把这一轮接稳。前排的位置，我陪你去问。' } },
        { id: 'count', label: '等一下，我把落点默记一遍。', detail: '在心里整理每一式的目标拍。', effects: { focus: 1 }, reply: { speaker: '嘉豪', text: '不急。记好了抬头，我等你。' } },
      ],
    },
    { speaker: '嘉豪', text: state => state.choices?.scattered_notes === 'together' ? '就像中午接纸那样。一人递出去，另一人接住。' : state.choices?.scattered_notes === 'organize' ? '就按你中午整理名单的办法，一式一式找到自己的位置。' : '中午你一开口，大家就跟上了。现在把那口气放稳。' },
    { speaker: '我', text: state => state.choices?.relay_plan === 'count' ? '二、三、二、四……记住了。好，开始吧。' : state.choices?.relay_plan === 'lead' ? '先做好眼前这一轮，再去想前排。' : '嗯。你的下一拍，我来接。' },
    { speaker: '嘉豪', text: '正式接拍前先做个不用听鼓点的。看我的重心和路线：直来宜让，虚引宜守，绕侧宜截。别抢答。' },
    { event: 'adventure', mode: 'spar', title: '拆招预演', id: 'spar' },
    { speaker: '我', text: state => challengeFor(state, 'spar').accuracy >= 80 ? '原来动作还没完全做出来，脚下的方向已经先说话了。' : '我看见动作了，但有几次还是被第一下带着跑。' },
    { speaker: '嘉豪', text: state => challengeFor(state, 'spar').correct >= 5 ? '读得不错。节拍告诉你什么时候动，读势告诉你为什么现在动。' : '不用把它当猜拳。先看脚和重心，手上的热闹最后再看。' },
    { speaker: '体育老师', text: '搭档接拍，预备——开始！' },
    { event: 'practice', mode: 'relay', title: '嘉豪的接拍试炼', id: 'relay' },
    { speaker: '我', text: state => resultFor(state, 'relay').accuracy >= 80 ? '最后一式收住的时候，我都没想数拍子。好像真的接上了。' : resultFor(state, 'relay').accuracy >= 50 ? '中间有几下跑偏了，不过我找到回来的地方了。' : '我有几次光顾着看你，忘记自己也有回合。再练一遍应该会好些。' },
    { speaker: '嘉豪', text: state => resultFor(state, 'relay').accuracy >= resultFor(state, 'standard').accuracy ? '你比上午更会等了。会等的人，反而不容易落下。' : '下午这个更难。别拿两个不同的练法罚自己，刚才你重新接回来了就算进步。' },
    { speaker: '体育老师', text: state => resultFor(state, 'relay').accuracy >= 70 ? '这一组，接拍不错。明天愿意的同学可以到前面试试示范。' : '这组练完了。明天继续，先看懂搭档的回合，再找自己的落点。' },
    { text: '队伍散开时，白线两侧留下两串浅浅的鞋印。没有谁把谁打败，只是两个人一起站完了一轮。' },
    { speaker: '嘉豪', text: state => state.choices?.first_reply === 'bold' ? '对了，早上借出去的称号，试用评价怎么样？' : state.choices?.first_reply === 'friendly' ? '早上你让我带路。今天这条路，算没带偏吧？' : '高一三班，嘉豪。上午记的那两个信息，现在还对得上吧？' },
    { speaker: '我', text: state => state.choices?.first_reply === 'bold' ? '名字听着挺响，实际业务包括找路、捡纸和数拍。还挺忙。' : state.choices?.first_reply === 'friendly' ? '没带偏。还顺便找到了一位搭档。' : '对得上。现在能在后面再加一条：接拍搭档。' },
    { text: state => state.focus >= 2 ? '我在本子角上记下了容易抢拍的那两式。今天还没会的东西，明天有地方接着练。' : state.courage >= 2 ? '“去前面试试”这个念头还留在心里。这次我没有急着把它划掉。' : '名单贴回了墙上。我的名字旁边，是今天刚记住的另一个名字。' },
    { speaker: '体育老师', text: '今天到这里。东西带齐，明天见。' },
    { event: 'scene', scene: 'afterSchool' },
    { text: '又走到早晨的校门口。相同的路，这次不用再确认往哪边走。' },
    { speaker: '嘉豪', text: state => endingFor(state) === 'together' ? '明天还是搭档？我在操场那条白线旁边等你。' : endingFor(state) === 'lead' ? '走，明天先去找老师报名。我说了，陪你问前排的位置。' : '明天见。哪一式没跟上，到时候再问我。' },
    { speaker: '我', text: state => endingFor(state) === 'together' ? '说好了。你起拍，我接；轮到我时，你也别走神。' : endingFor(state) === 'lead' ? '好。名字先写上，剩下的认真练。' : state.focus >= 2 ? '我记下来了。明天先把那两拍接好。' : '明天见。今天这几拍，我回去还想再记一遍。' },
    { speaker: '嘉豪', text: state => endingFor(state) === 'together' ? '放心。这次连标签都替你看着。' : endingFor(state) === 'lead' ? '那明早别迟到。站前排可没那么容易混进队伍。' : '行。还有，校服标签记得剪。' },
    { text: '新学期的第一天，结束在一句“明天见”里。有些事还不熟练，有些名字却已经记住了。' },
    { event: 'ending' },
  ];

  window.WushuStory = { scenes, story };
})();
