(() => {
  // 剧情与编排为原创。voice / music 为 null 时不请求新素材，沿用已有配乐。
  // when 控制台词是否出现；选择只影响剧情关系，不改变练习的判定窗口。
  const scenes = {
    gate: { title: '第一章 · 名字先记住', image: 'resources/scene/sight/1.webp', music: 'school' },
    yard: { title: '第二章 · 后排也有节拍', image: 'resources/scene/sight/yard_assembly.webp', music: 'school' },
    exercise: { title: '第三章 · 八式初试', image: 'resources/scene/sight/wushu_practice_homage.webp', music: 'school' },
    lunch: { title: '第四章 · 被风吹乱的名单', image: 'resources/scene/sight/courtyard_wind_original.webp', music: 'comedy' },
    relay: { title: '第五章 · 你的下一拍', image: 'resources/scene/sight/wushu_practice_homage.webp', music: 'school' },
    afterSchool: { title: '终章 · 明天见', image: 'resources/scene/sight/1.webp', music: 'school' },
  };
  const resultFor = (state, mode) => state.practiceResults?.[mode] || {};
  const challengeFor = (state, mode) => state.adventureResults?.[mode] || {};
  const endingFor = state => state.rapport >= 2 ? 'together' :
    state.courage >= 2 && resultFor(state, 'relay').accuracy >= 70 ? 'lead' : 'steady';
  const story = [
    { text: '多么好的上午啊！' },
    { text: '花儿在绽放。' },
    { text: '鸟儿在歌唱。' },
    { text: '新学期也开始了。' },
    { speaker: '我', text: '这就是高中吗……有点期待呢。', when: state => state.character === '女同学', voice: null },
    { speaker: '我', text: '区区高中，不足挂齿，你豪王来了！', when: state => state.character !== '女同学', voice: 'resources/sound/human/male/school_open1.mp3' },
    { speaker: '我', text: '“豪王到此一游”……开学第一天，留言板上就有人给自己起外号了？', when: state => state.character === '女同学', voice: null },
    { text: '从背后传来声音：' },
    { speaker: '？？？', text: 'Oi！小鬼，你刚才提到了豪王是吗？', voice: 'resources/sound/human/male/school_open2.mp3' },
    { event: 'jiahaoEntrance' },
    { speaker: '我', text: '你……是谁？' },
    { speaker: '？？？', text: '天不生你豪哥，万古白昼如长夜。吾乃嘉豪是也！', effect: { kind: 'divine', kicker: '高一三班 · 限定登场', title: '神 明 降 临', caption: '战力：未知　校服：学校统一发放' } },
    { speaker: '我（心里）', text: '这学校报到之前，还要先报江湖名号吗？' },
    { text: '他把手从口袋里抽出来。我下意识站直了。' },
    { speaker: '嘉豪', text: '神是不会眷顾凡人的，但我看你顺眼，享受这份荣耀吧！' },
    { text: '他指了指我露出的校服标签。那根手指在半空停了两秒，似乎在等我谢恩。' },
    {
      event: 'choice', id: 'first_reply', prompt: '把标签塞回去之后，你决定——',
      options: [
        { id: 'bold', label: '称号先借我一天。', detail: '顺着玩笑接一句。', effects: { courage: 1 }, reply: { speaker: '嘉豪', text: '想当我在人间的代言人吗？有意思，就先今天吧。' } },
        { id: 'friendly', label: '假装没看见。', detail: '神经貌似不正常。', effects: { rapport: 1 }, reply: { speaker: '嘉豪', text: '去教学楼吗？正好顺路，作为随从跟着我吧。' } },
        { id: 'careful', label: '名字记住了，几班的？', detail: '先把有用的信息弄清楚。', effects: { focus: 1 }, reply: { speaker: '嘉豪', text: '高一三班。在凡间的躯壳罢了。' } },
      ],
    },
    { speaker: '我', text: state => state.choices?.first_reply === 'bold' ? '包午饭吗？不包的话，神谕我只传半句。' : state.choices?.first_reply === 'friendly' ? '我去三班。你要是也去，就别挡路。' : '那躯壳把学生证拿出来，我核实一下。', effect: state => state.choices?.first_reply === 'bold' ? { kind: 'receipt', kicker: '豪王工作室 · 招聘现场', title: '待遇谈崩了', caption: '五险一金：无　午饭：自理　神谕：按条结算' } : state.choices?.first_reply === 'friendly' ? { kind: 'crash', kicker: '气场攻击判定', title: '对方拒绝接戏', caption: '神威没有命中任何目标' } : { kind: 'receipt', kicker: '神明身份核验', title: '请出示学生证', caption: '职业：在校学生　神职：本人自称' } },
    { speaker: '嘉豪', text: '凡人总是在意这些细枝末节。算了，随我——' },
    { speaker: '门卫', text: '嘉豪！刚才在留言板上写字的，回来擦干净！' },
    { text: '神的脚步停了。神从口袋里掏出一块湿抹布。准备得异常充分。', effect: { kind: 'crash', kicker: '神格认证失败', title: '被 门 卫 单 防', caption: '掉落装备：湿抹布 × 1' } },
    { speaker: '我', text: '你这是第几次下凡了？' },
    { speaker: '嘉豪', text: '……不要打听神的工作经历。' },
    { speaker: '广播', text: '请高一年级全体同学到操场集合，准备进行武术操入门练习。' },
    { speaker: '我', text: '第一天就练武？我的书包都还没找到落脚的地方。' },
    { speaker: '嘉豪', text: '走。待本座擦除天机，带你去见识一下真正的武学。' },
    { text: '我跟着嘉豪穿过人群。前方的口令声，渐渐清晰起来。' },
    { event: 'scene', scene: 'yard' },
    { text: '嘉豪背着手，径直走进一支队伍。我刚跟上，前面的人就递来一面小旗。' },
    { speaker: '带队老师', text: '志愿者到了？正好，带家长去礼堂。' },
    { speaker: '我', text: '你们神界报到还允许带家长？' },
    { speaker: '嘉豪', text: '此乃……旁支任务。', effect: { kind: 'quest', kicker: '支线任务 · 意外解锁', title: '护送家长前往礼堂', caption: '任务奖励：错过本班点名' } },
    { speaker: '体育委员', text: '高一三班在这边！拿旗那个，别把新同学带走！' },
    { text: '我们赶在点名前站进最后一排。阳光越过前排同学的肩膀，一格一格落在地上。' },
    { speaker: '体育老师', text: '前后左右留出距离。今天先熟悉动作，整齐比抢快重要。' },
    { speaker: '嘉豪', text: '最后一排适合封印实力。免得本座一出手，扰乱天地秩序。' },
    { speaker: '我', text: '刚才天地秩序差点被你带去礼堂。' },
    { speaker: '体育老师', text: '先记住四拍。每一式的重点不一定在同一拍，听清再动。' },
    { speaker: '我', text: '原来第一课是克制一下“我已经懂了”的冲动。' },
    { speaker: '嘉豪', text: '本座当然懂。只是这具身体尚未完成同步。', effect: { kind: 'buffer', kicker: '脑子：我会了', title: '身体正在缓冲', caption: '当前进度：1%　预计完成：下次一定' } },
    { event: 'scene', scene: 'exercise' },
    { speaker: '体育老师', text: '全体都有——立正！' },
    { text: '操场渐渐安静下来。嘉豪收起笑，我也跟着站好。' },
    { speaker: '体育老师', text: '抱拳，行礼！' },
    { text: '衣袖轻轻擦过。我忽然觉得，刚才闹哄哄的一群人，好像真的成了一支队伍。' },
    { speaker: '体育老师', text: '今天走一套“八式巡礼”：向地术、六合、虎尊、香店、鸣鹤、檀家、咏春、罗汉八脉借一点形与劲。抱拳起，鹤引展，虎步落，最后归元。' },
    { speaker: '嘉豪', text: '不是把八套拳硬塞进八拍，是记住它们的脾气：有的稳根，有的合劲，有的刚猛，有的像鹤一样舒展。' },
    { speaker: '我', text: '你刚才不是说，看一遍就能全部拿下？' },
    { speaker: '嘉豪', text: '当然。等我解除封——' },
    { speaker: '体育老师', text: '最后一排那位，一直讲话的是很熟练吧？下午和你旁边的同学做一组示范。' },
    { text: '嘉豪缓缓把伸到一半的手放下。我的名字还没被老师记住，人已经被他打包送出去了。', effect: { kind: 'quest', kicker: '主线任务 · 被迫接取', title: '你俩，下午来示范', caption: '队友发起了团战，并替你点击了同意' } },
    { speaker: '我', text: '你解除的是谁的封印？我的？' },
    { speaker: '嘉豪', text: '莫慌。到时听我号令。' },
    { speaker: '体育老师', text: '每一式考的东西不同：礼要左右合拍，鹤要找准风门，虎步要蓄力落稳，罗汉推掌要把力量持续送出去。别只会追鼓点。' },
    { speaker: '嘉豪', text: '本座已看穿全部试炼。' },
    { text: '他趁老师转身，飞快低头瞄了一眼掌心。上面写着“左右别反”。', effect: { kind: 'receipt', kicker: '秘籍鉴定结果', title: '手 心 外 挂', caption: '离线可用　遇汗失效　不支持左右自动识别' } },
    { event: 'forms', title: '八式百炼 · 初试', id: 'standard' },
    { speaker: '体育老师', text: state => resultFor(state, 'standard').accuracy >= 80 ? '后排那位新同学，八项都抓住了重点。很好，接下来试着把不同的劲连成一套。' : '第一次练完了，先记住自己最顺的一式。下一次从它开始，再把不熟的规则一项项接回来。' },
    { speaker: '我', text: state => resultFor(state, 'standard').bestCombo >= 5 ? '规则一直在变，身体居然还是能一式接一式地跟上。' : '脑子说八种玩法都懂了，手说它还需要开个会。' },
    { speaker: '嘉豪', text: state => resultFor(state, 'standard').accuracy >= 80 ? '不错。能跟上本座挑选搭档的眼光。' : '第一次而已。神也不是……咳，总之下午还有本座。' },
    { speaker: '我', text: '你手上的“左右别反”蹭脸上了。' },
    { text: '嘉豪擦了把脸。现在两边都写着“左”。', effect: { kind: 'crash', kicker: '人体导航发生异常', title: '左 右 都 是 左', caption: '正在重新规划路线……' } },
    { speaker: '体育老师', text: '休息。下午做接拍练习，两人轮流示范。体育委员，午休前把分组名单贴好。' },
    { event: 'scene', scene: 'lunch' },
    { text: '午间，体育委员把分组名单放在长椅上。嘉豪顺手抽出压着名单的蓝色本子，拍在我面前。' },
    { speaker: '嘉豪', text: '下午能否登临绝顶，就看这本——' },
    { text: '风先登临了。失去镇压的名单哗啦飞起，一张直接糊在嘉豪脸上。', effect: { kind: 'crash', kicker: '环境伤害', title: '被 A4 纸 单 杀', caption: '豪王 0 : 1 自然风' } },
    { speaker: '我', text: '绝顶先等等。你把镇纸拿走了。' },
    { speaker: '体育委员', text: '别让分组名单飞到水沟里！上面还有老师写的备注！' },
    { speaker: '我', text: '我这张写着“番茄炒蛋”。它负责哪一组？' },
    { speaker: '嘉豪', text: '背面！还有蓝色本子里掉出来的那张，不许看！' },
    {
      event: 'choice', id: 'scattered_notes', prompt: '几张纸散在队伍旁边，你先怎么帮忙？',
      options: [
        { id: 'together', label: '和嘉豪一张张收回来。', detail: '一人捡纸，一人压住，配合着来。', effects: { rapport: 1 }, reply: { speaker: '嘉豪', text: '你递，我压着。这次风想插队也没用。' } },
        { id: 'organize', label: '先把页码和班级对上。', detail: '把手里几张按顺序整理好。', effects: { focus: 1 }, reply: { speaker: '体育委员', text: '太好了，我刚才差点把菜单也贴上去。' } },
        { id: 'call_out', label: '叫住前面几个人一起捡。', detail: '主动招呼大家分头帮忙。', effects: { courage: 1 }, reply: { speaker: '同班同学', text: '收到！靠水沟那两张交给我们。' } },
      ],
    },
    { text: state => state.choices?.scattered_notes === 'together' ? '我负责追页码，嘉豪负责压住收回的纸。剩下几张还在风里打转。' : state.choices?.scattered_notes === 'organize' ? '我先看清页码，再朝散页跑去。找准顺序，应该比看见一张抓一张更快。' : '几个人应声分散开来。我盯住名单上的红色页码，免得把午饭菜单也混进去。' },
    { event: 'adventure', mode: 'paper', title: '风中名单', id: 'paper' },
    { speaker: '体育委员', text: state => challengeFor(state, 'paper').correct === challengeFor(state, 'paper').total ? challengeFor(state, 'paper').errors === 0 ? '一张没漏，顺序也全对！你是不是平时专门跟风抢东西？' : '名单齐了！中间那几张菜单我就当没看见。' : '先收回这些，剩下的我去水沟边找。至少班级和场地页都保住了。' },
    { speaker: '嘉豪', text: state => challengeFor(state, 'paper').grade === 'S' ? '眼睛挺快，手也没乱。看来豪王还兼任文书。' : '风比口令不讲道理。看清下一张再追，反而更快。' },
    { text: '最后一张纸挂在他书包扣上。我摘下来，正面是“豪王登神计划”，背面是歪歪扭扭的八式动作。', effect: { kind: 'quest', kicker: '发现关键道具', title: '豪王登神计划', caption: '物品描述：本人强烈要求不要点开' } },
    { speaker: '我', text: '第一步：用气场结交同学。第二步：武术操一鸣惊人。第三步……怎么空着？' },
    { speaker: '嘉豪', text: '天机不可写尽。还我。' },
    { text: '“一鸣惊人”下面被划掉过三次。纸角写着：紧张就看搭档，别一直看地。' },
    { speaker: '我', text: '你其实也怕下午出错？' },
    { speaker: '嘉豪', text: '……初中上台，我朝左，全班朝右。我妈到现在还拿那段视频给亲戚看。' },
    { speaker: '我', text: '原来是有战绩。' },
    { speaker: '嘉豪', text: '笑吧。趁下午还没轮到你。' },
    { text: '我把那张纸折好塞回蓝色本子。刚才还一脸戒备的神，终于松开了攥着书包带的手。' },
    { speaker: '我', text: '第三步先写吃饭。下午要是忘动作，就看我，别看地。' },
    { speaker: '嘉豪', text: '……准奏。但番茄炒蛋各买各的，本座没带那么多钱。', effect: { kind: 'receipt', kicker: '神界财务部通知', title: '神力不可抵扣餐费', caption: '本店支持饭卡，不支持渡劫' } },
    { event: 'scene', scene: 'relay' },
    { speaker: '体育老师', text: '下午换个练法：先看搭档示范，再在自己的回合接上。上午说很熟练的那组，准备好了就来前面。' },
    { text: '嘉豪往左挪一步，我往右挪一步。老师的目光停在我们中间，谁也没躲掉。' },
    { speaker: '嘉豪', text: '我先示范，你再接。轮到我时先看提示，轮到你再出招，别抢我的回合。' },
    { text: '我们先站到旁边的白线两侧试动作。嘉豪第三次整理衣领，这次标签根本没露出来。' },
    {
      event: 'choice', id: 'relay_plan', prompt: '开始前，给搭档留一句话。',
      options: [
        { id: 'listen', label: '我听着呢，放心起拍。', detail: '把注意力放在彼此的配合上。', effects: { rapport: 1 }, reply: { speaker: '嘉豪', text: '好。你接你的，我也会看着你。' } },
        { id: 'lead', label: '待会儿我来带头。', detail: '主动接过示范的第一轮。', effects: { courage: 1 }, reply: { speaker: '嘉豪', text: '好。本座负责……在你后面兜底。' } },
        { id: 'count', label: '等一下，我把落点默记一遍。', detail: '在心里整理每一式的目标拍。', effects: { focus: 1 }, reply: { speaker: '嘉豪', text: '不急。记好了抬头，我等你。' } },
      ],
    },
    { speaker: '嘉豪', text: state => state.choices?.scattered_notes === 'together' ? '就像中午接纸那样。一人递出去，另一人接住。' : state.choices?.scattered_notes === 'organize' ? '就按你中午整理名单的办法，一式一式找到自己的位置。' : '中午你一开口，大家就跟上了。现在把那口气放稳。' },
    { speaker: '我', text: state => state.choices?.relay_plan === 'count' ? '二、三、二、四……记住了。好，开始吧。' : state.choices?.relay_plan === 'lead' ? '行，忘了就看我。别又全班向右你向左。' : '嗯。你的下一拍，我来接。' },
    { speaker: '嘉豪', text: '正式接拍前先做个不用听鼓点的。看我的重心和路线：直来宜让，虚引宜守，绕侧宜截。别抢答。' },
    { event: 'adventure', mode: 'spar', title: '拆招预演', id: 'spar' },
    { speaker: '我', text: state => challengeFor(state, 'spar').accuracy >= 80 ? '原来动作还没完全做出来，脚下的方向已经先说话了。' : '我看见动作了，但有几次还是被第一下带着跑。' },
    { speaker: '嘉豪', text: state => challengeFor(state, 'spar').correct >= 5 ? '读得不错。节拍告诉你什么时候动，读势告诉你为什么现在动。' : '不用把它当猜拳。先看脚和重心，手上的热闹最后再看。' },
    { speaker: '体育老师', text: '你们两个，来。大家看这一组怎么接。' },
    { text: '我们刚站好，音箱“嘟”了一声。紧接着，一个陌生的女声响彻操场：“您的设备电量低。”' },
    { speaker: '我', text: '神谕？' },
    { speaker: '嘉豪', text: '不是我的。', effect: { kind: 'battery', kicker: '操场音箱 · 剧情提示', title: '神力不足 1%', caption: '建议连接电源，或暂时停止装高手' } },
    { text: '体育委员蹲下换备用音箱。等他重新站起来，后排已经有人模仿起了那句“电量低”。' },
    { speaker: '后排同学', text: '豪哥还有电吗？' },
    { speaker: '嘉豪', text: '满——' },
    { text: '他的声音卡了一下。我用鞋尖轻轻碰了碰他脚边的白线。嘉豪低头看了一眼，又抬起头。' },
    { speaker: '我', text: state => state.choices?.relay_plan === 'lead' ? '这轮我先来。跟上，神明大人。' : state.choices?.relay_plan === 'count' ? '别管他们。按刚才记的来。' : '我在呢。你起拍。' },
    { speaker: '嘉豪', text: '……看好了。本座只演示一次。', effect: { kind: 'divine', kicker: '检测到搭档在场', title: '神 力 续 上 了', caption: '本次充电来源：旁边那个没有走的人' } },
    { speaker: '体育老师', text: '音箱好了。搭档接拍，预备——开始！' },
    { event: 'practice', mode: 'relay', title: '嘉豪的接拍试炼', id: 'relay' },
    { speaker: '我', text: state => resultFor(state, 'relay').accuracy >= 80 ? '最后一式收住的时候，我都没想数拍子。好像真的接上了。' : resultFor(state, 'relay').accuracy >= 50 ? '中间有几下跑偏了，不过我找到回来的地方了。' : '我有几次光顾着看你，忘记自己也有回合。再练一遍应该会好些。' },
    { speaker: '嘉豪', text: state => resultFor(state, 'relay').accuracy >= resultFor(state, 'standard').accuracy ? '你比上午更会等了。会等的人，反而不容易落下。' : '下午这个更难。别拿两个不同的练法罚自己，刚才你重新接回来了就算进步。' },
    { speaker: '体育老师', text: state => resultFor(state, 'relay').accuracy >= 70 ? '这一组，接拍不错。明天愿意的同学可以到前面试试示范。' : '这组练完了。明天继续，先看懂搭档的回合，再找自己的落点。' },
    { text: '队伍散开时，白线两侧留下两串浅浅的鞋印。没有谁把谁打败，只是两个人一起站完了一轮。' },
    { speaker: '嘉豪', text: state => state.choices?.first_reply === 'bold' ? '对了，人间代言人。今日神迹，评价如何？' : state.choices?.first_reply === 'friendly' ? '早上你还假装没看见本座。现在知道跟着谁混了吧？' : '高一三班，嘉豪。凡间躯壳的名字，记牢了？' },
    { speaker: '我', text: state => state.choices?.first_reply === 'bold' ? '擦留言板、带错路、掀飞名单。业务很多，建议先买保险。' : state.choices?.first_reply === 'friendly' ? '知道了。跟着你，一天能赔三次不是。' : '记牢了。尤其是你把家长志愿者的旗递给我的时候。' },
    { text: '嘉豪翻开蓝色本子，把“结交同学”后面打了个勾。我看见了，没说破。', effect: { kind: 'quest', kicker: '登神计划 · 第一步', title: '结交同学 ✓', caption: '这一次，确实完成了。' } },
    { text: state => state.focus >= 2 ? '我在本子角上记下了容易抢拍的那两式。今天还没会的东西，明天有地方接着练。' : state.courage >= 2 ? '“去前面试试”这个念头还留在心里。这次我没有急着把它划掉。' : '名单贴回了墙上。我的名字旁边，是今天刚记住的另一个名字。' },
    { speaker: '体育老师', text: '今天到这里。东西带齐，明天见。' },
    { event: 'scene', scene: 'afterSchool' },
    { text: '又走到早晨的校门口。相同的路，这次不用再确认往哪边走。' },
    { speaker: '嘉豪', text: state => endingFor(state) === 'together' ? '明天还是搭档？我在操场那条白线旁边等你。' : endingFor(state) === 'lead' ? '走，明天先去找老师报名。我说了，陪你问前排的位置。' : '明天见。哪一式没跟上，到时候再问我。' },
    { speaker: '我', text: state => endingFor(state) === 'together' ? '说好了。你起拍，我接；轮到我时，你也别走神。' : endingFor(state) === 'lead' ? '好。名字先写上，剩下的认真练。' : state.focus >= 2 ? '我记下来了。明天先把那两拍接好。' : '明天见。今天这几拍，我回去还想再记一遍。' },
    { speaker: '嘉豪', text: state => endingFor(state) === 'together' ? '放心。本座准许你继续并肩而行。' : endingFor(state) === 'lead' ? '那明早别迟到。本座可不会替你向凡人老师求情。' : '行。还有，校服标签记得剪。神不做售后。' },
    { speaker: '门卫', text: '嘉豪！站住！' },
    { speaker: '嘉豪', text: '已经擦了！抹布也洗了！' },
    { speaker: '门卫', text: '你妈刚打电话，说你忘带家门钥匙了，在门口等她。', effect: { kind: 'crash', kicker: '返回神域失败', title: '缺 少 关 键 道 具', caption: '家门钥匙 × 1　　请等待母上大人上线' } },
    { text: '神沉默了。几秒后，他慢慢转向我。' },
    { speaker: '嘉豪', text: '……陪本座坐会儿？' },
    { speaker: '我', text: '行。这次不收代言费。' , when: state => state.choices?.first_reply === 'bold' },
    { speaker: '我', text: '行。凡间的躯壳也得等家长。', when: state => state.choices?.first_reply !== 'bold' },
    { text: '我们坐在校门边的长椅上。嘉豪把本子往里收了收，给我腾出半个位置。' },
    { event: 'ending' },
  ];

  // 旧版按台词下标存档；扩写后映射到对应台词，保留选择和挑战成绩。
  const legacyIndices = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,23,24,25,26,27,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,53,54,56,57,58,59,62,63,64,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,87,88,90,91,92,93,94,95,96,97,98,99,110,111,112,113,114,115,116,118,119,120,121,122,123,124,125,133];
  window.WushuStory = { scenes, story, legacyIndices };
})();
